language: java

jdk:
 - oraclejdk11


secure: "pEUhO4aENjtDqtdYylvheWsMxaO52oakKgGUQdo/2NyZkB9UXC5Smt9JSTrBBXfhaWFv65t8K86qkESspIDpD12Q33FLCTpFiJBzyKYxswgmSpjiFi9oiyStxB3PkqfvsKqq2SkQwEBaMmtcjYhQ/izy3V90Winwamv5+Gcqx4e9/TOUYTei7B9YF58hwjpo8DJbxTPzQf6EwxXwl1VC5uqBOGeCf9CIOexFNQPLHWC4CfI+hLSAocneKbo09e5t1Sh+3JJIgwMatToIbLyxqxqX4V5NrZc8/Vt0IgJvud+gLYt26xtUc/o8G9lQTWsMrv2Ic/osnVCnGseDDEohkiyyoiUDSzP+LgNwebqDLJKvWJhrp6qWMEV49qZGOLns7zdD56si4Y5t3uRQeADQRrpS9Gh5jSqHqn+Hht2c+wZ6nLlNoK8Z8xXCTJWnR7GpFdEMJQozjSNU14RSEvZJ2CgJIgi7z/+LeHb7S2CuxYMsPcJbmu/tRNzUVstRGG6Pi8Is0smSgf+S+qiXqhO6U+GEK7WZTE3PQm8+cJsa1ugNFJ0Cuj6Oehfvmoq645POElB5a57RuB6k+M1KQ/yxWz7bF2yOHgjsiQc94qHsWK12XRkOlg0xriEtPdQlA+IwZtNh0m9APKBrQhH4a7MnYOyfBz+F6DcZZMr5gJcuuks="

script:
- mvn clean verify

after_deploy:
- echo "done deploying"